config/routes.rb
Rails.application.routes.draw do

  get 'rooms/index'

  resources :teachers do
    collection do
        get 'add_students_to_teachers'
    end
  end
  resources :students

  resources :events
  resources :clubs
  
  

  resources :rooms do
    resources :messages
  end

  get 'site/index'
  get 'site/show_users'
  get 'site/one_to_many'
  get 'site/many_to_many'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "site#index"

end

app/models/student.rb
class Student < ApplicationRecord
    has_and_belongs_to_many :teachers
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>
<div class="text-center">
<%= render "form", student: @student %>

<br>

<div>
  <%= button_to "Show this student", @student, method: :get, class: "btn btn-primary m-1" %> 
  <%= button_to "Back to students", students_path, method: :get, class: "btn btn-secondary m-1" %>
</div> 
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>



<h1><u>Students</u></h1>
<div class="text-center">
<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= button_to "Show this student", student, method: :get, class: "btn btn-primary m-1" %>
    </p>
  <% end %>
</div>

<%= button_to "New student", new_student_path, method: :get, class: "btn btn-success m-1" %>
</div>

app/views/students/new.html.erb
<h1>New student</h1>
<div class="text-center">
<%= render "form", student: @student %>

<br>

<div>
  <%= button_to "Back to students", students_path, method: :get, class: "btn btn-secondary m-1" %>
</div>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="text-center">
<%= render @student %>

<div>
  <%= button_to "Edit this student", edit_student_path(@student), method: :get, class: "btn btn-warning m-1" %> 
  <%= button_to "Back to students", students_path, method: :get, class: "btn btn-secondary m-1" %>

  <%= button_to "Destroy this student", @student, method: :delete, class: "btn btn-dark m-1" %>
</div>
</div>