config/routes.rb
Rails.application.routes.draw do

  get 'rooms/index'

  resources :teachers do
    collection do
        get 'add_students_to_teachers'
    end
  end
  resources :students

  resources :events
  resources :clubs
  
  

  resources :rooms do
    resources :messages
  end

  get 'site/index'
  get 'site/show_users'
  get 'site/one_to_many'
  get 'site/many_to_many'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "site#index"

end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_and_belongs_to_many :students
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[ show edit update destroy ]

  # GET /teachers or /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1 or /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers or /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully created." }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1 or /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully updated." }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1 or /teachers/1.json
  def destroy
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url, notice: "Teacher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_students_to_teachers
    @teachers=Teacher.all
    @students=Student.all
    if params[:teacher_id] !=nil
    t=@teachers.find(params[:teacher_id])
    s=@students.find(params[:student_id])
    t.students<<s
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teacher_params
      params.require(:teacher).permit(:name)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher) do |form| %>
  <% if teacher.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
        <% teacher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/_teacher.html.erb
<div id="<%= dom_id teacher %>" class="border border-black">
  <p class="border border-black">
    <strong>Name:</strong>
    <%= teacher.name %>
  </p> 
  <strong>Students:</strong>
  <% teacher.students.each do |s| %>
    <p>
      <%= link_to s.name, student_path(id:s.id) %>
    </p>
  <%end%>

</div>

app/views/teachers/add_students_to_teachers.html.erb
<%= form_with url: "/teachers/add_students_to_teachers", method: :get do |form| %>
  <div class="row p-3">
    <div class="col-lg-6 text-center">
      <%= form.label :teacher_id, "Teacher:" %>
      <%= form.select :teacher_id, options_from_collection_for_select(@teachers, 'id', 'name')%>
    </div>
    <div class="col-lg-6 text-center ">
      <%= form.label :student_id, "Student:" %>
      <%= form.select :student_id, options_from_collection_for_select(@students, 'id', 'name')%>
    </div> 
  </div>
  <div class="text-center">
    <%= form.submit %>
  </div> 
  
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>
<div class="text-center">
<%= render "form", teacher: @teacher %>

<br>

<div>
  <%= button_to "Show this teacher", @teacher, method: :get, class: "btn btn-primary m-1" %> 
  <%= button_to "Back to teachers", teachers_path, method: :get, class: "btn btn-secondary m-1" %>
</div>
</div>

app/views/teachers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><u>Teachers</u></h1>

<div class="text-center">



<div id="teachers">
  <% @teachers.each do |teacher| %>
    <%= render teacher %>
    <p>
      <%= button_to "Show this teacher", teacher, method: :get, class: "btn btn-primary m-1" %>
    </p>
  <% end %>
</div>

<%= button_to "New teacher", new_teacher_path, method: :get, class: "btn btn-success m-1" %>
<%= button_to "Assign students to teachers", add_students_to_teachers_teachers_path , method: :get, class: "btn btn-info m-1"%> 
</div>

app/views/teachers/new.html.erb
<h1>New teacher</h1>
<div class="text-center">
<%= render "form", teacher: @teacher %>

<br>

<div>
  <%= button_to "Back to teachers", teachers_path, method: :get, class: "btn btn-secondary m-1" %>
</div>
</div>

app/views/teachers/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="text-center">
<%= render @teacher %>

<div>
  <%= button_to "Edit this teacher", edit_teacher_path(@teacher), method: :get, class: "btn btn-warning m-1" %> 
  <%= button_to "Back to teachers", teachers_path, method: :get, class: "btn btn-secondary m-1" %>

  <%= button_to "Destroy this teacher", @teacher, method: :delete, class: "btn btn-dark m-1" %>
</div>
</div>