config/routes.rb
Rails.application.routes.draw do

  get 'rooms/index'

  resources :teachers do
    collection do
        get 'add_students_to_teachers'
    end
  end
  resources :students

  resources :events
  resources :clubs
  
  

  resources :rooms do
    resources :messages
  end

  get 'site/index'
  get 'site/show_users'
  get 'site/one_to_many'
  get 'site/many_to_many'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "site#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/club.rb
class Club < ApplicationRecord
    has_many :events
end

app/models/event.rb
class Event < ApplicationRecord

    belongs_to :club

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to self.room }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages

  validates_uniqueness_of :name
  after_create_commit {broadcast_append_to "rooms"}
end

app/models/student.rb
class Student < ApplicationRecord
    has_and_belongs_to_many :teachers
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_and_belongs_to_many :students
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_uniqueness_of :name
  scope :all_except, ->(user) { where.not(id: user) }
  has_many :messages
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: %i[ show edit update destroy ]

  # GET /clubs or /clubs.json
  def index
    @clubs = Club.all
  end

  # GET /clubs/1 or /clubs/1.json
  def show 
    
  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs or /clubs.json
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to club_url(@club), notice: "Club was successfully created." }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1 or /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to club_url(@club), notice: "Club was successfully updated." }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1 or /clubs/1.json
  def destroy
    @club.destroy

    respond_to do |format|
      format.html { redirect_to clubs_url, notice: "Club was successfully destroyed." }
      format.json { head :no_content }
    end
  end 

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def club_params
        params.require(:club).permit(:title)
      end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new 
    @clubs=Club.all
  end

  # GET /events/1/edit
  def edit 
    @clubs=Club.all
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :club_id, :startdate, :enddate)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @current_user = current_user
    @message = @current_user.messages.create(content: msg_params[:content], room_id: params[:room_id])
  end

  private

  def msg_params
    params.require(:message).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @current_user = current_user
    @rooms = Room.all
    @users = User.all_except(@current_user)
    @room = Room.new
  end

  def show
    @current_user = current_user
    @single_room = Room.find(params[:id])
    @rooms = Room.all
    @users = User.all_except(@current_user)
    @room = Room.new
    @message = Message.new
    @messages = @single_room.messages
  
    render "index"
  end

  def create
    @room = Room.create(name: params["room"]["name"])
  end

  def destroy
    redirect_to rooms_path
    @single_room = Room.find(params[:id])
    @single_room.messages.destroy_all
    @single_room.destroy
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end

  def show_users
    @users = User.all
  end

  def one_to_many
    @clubs = Club.all
    @events = Event.all
  end

  def many_to_many
    @students = Student.all
    @teachers = Teacher.all
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_room ,@message], remote: true, class: "d-flex" ) do |f| %>
    <%= f.text_field :content, id: 'chat-text', class: "form-control", autocomplete: 'off' %>
    <%= f.submit data: { disable_with: false }, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class: "d-flex" ) do |f| %>
  <%= f.text_field :name, class: "form-control", autocomplete: 'off' %>
  <%= f.submit data: { disable_with: false } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CharltonMs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <%= stylesheet_link_tag "custom" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <style>
      <%= ".msg-#{current_user&.id}" %> {
      background-color: #007bff !important;
      padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
      display: flex;
      justify-content: flex-end
      }
    </style>
  </head>
  <body>
    <% if  user_signed_in? %>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <button class="btn btn-link nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                Database
              </button>
              <ul class="dropdown-menu dropdown-menu">
                <li><%= link_to "Users", site_show_users_path, class: "nav-link" %></li>
                <li><%= link_to "One-to-Many", site_one_to_many_path, class: "nav-link" %></li>
                <li><%= link_to "Many-to-Many", site_many_to_many_path, class: "nav-link" %></li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <button class="btn btn-link nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                CRUD
              </button>
              <ul class="dropdown-menu dropdown-menu">
                <li><%= link_to "Events", events_path, class: "nav-link" %></li>
                <li><%= link_to "Clubs", clubs_path, class: "nav-link" %></li>
                <li><%= link_to "Teachers", teachers_path, class: "nav-link" %></li>
                <li><%= link_to "Students", students_path, class: "nav-link" %></li>
              </ul>
            </li>
            <li class="nav-item">
              <%= link_to "Chat", rooms_path, class: 'nav-link' %>
            </li>
          </ul>

        </div>
        <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
      </div>
    </nav>
    <% end %> 
    <div class="container" >
      <%= yield %> 
    </div>
  </body>
</html>